In [7]:
from siformer.model import SiFormer
import math
import torch

In [2]:
print(SiFormer.get_encoding_table().shape)

torch.Size([1, 204, 108])


In [3]:
print(SiFormer.get_encoding_table()[0,:5,:4])


tensor([[ 0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403,  0.7468,  0.6651],
        [ 0.9093, -0.4161,  0.9933, -0.1153],
        [ 0.1411, -0.9900,  0.5745, -0.8185],
        [-0.7568, -0.6536, -0.2291, -0.9734]])


tensor([[ 0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403,  0.7468,  0.6651],
        [ 0.9093, -0.4161,  0.9933, -0.1153],
        [ 0.1411, -0.9900,  0.5745, -0.8185],
        [-0.7568, -0.6536, -0.2291, -0.9734]])


In [41]:
def get_encoding_table(d_model=108, seq_len=204):
    torch.manual_seed(42)
    tensor_shape = (seq_len, d_model)
    frame_pos = torch.rand(tensor_shape)
    for i in range(tensor_shape[0]):
        for j in range(1, tensor_shape[1]):
            frame_pos[i, j] = frame_pos[i, j - 1]
    frame_pos = frame_pos.unsqueeze(1)  # (seq_len, 1, feature_size): (204, 1, 108)
    return frame_pos

In [42]:
print(get_encoding_table())

tensor([[[0.8823, 0.8823, 0.8823,  ..., 0.8823, 0.8823, 0.8823]],

        [[0.0624, 0.0624, 0.0624,  ..., 0.0624, 0.0624, 0.0624]],

        [[0.5723, 0.5723, 0.5723,  ..., 0.5723, 0.5723, 0.5723]],

        ...,

        [[0.8311, 0.8311, 0.8311,  ..., 0.8311, 0.8311, 0.8311]],

        [[0.5945, 0.5945, 0.5945,  ..., 0.5945, 0.5945, 0.5945]],

        [[0.2553, 0.2553, 0.2553,  ..., 0.2553, 0.2553, 0.2553]]])


In [35]:
def get_encoding_table_new(d_model=108, seq_len=204):
    position = torch.arange(seq_len).unsqueeze(1)
    div_term = torch.exp(torch.arange(0, d_model, 2) * (-math.log(10000.0) / d_model))
    pe = torch.zeros(seq_len, 1, d_model)
    pe[:, 0, 0::2] = torch.sin(position * div_term)
    pe[:, 0, 1::2] = torch.cos(position * div_term)
    return pe

def get_encoding_table(d_model=108, seq_len=204):
    torch.manual_seed(42)
    tensor_shape = (seq_len, d_model)
    frame_pos = torch.rand(tensor_shape)
    for i in range(tensor_shape[0]):
        for j in range(1, tensor_shape[1]):
            frame_pos[i, j] = frame_pos[i, j - 1]
    frame_pos = frame_pos.unsqueeze(1)  # (seq_len, 1, feature_size): (204, 1, 108)
    return frame_pos

In [34]:
print('get_encoding_table: ',get_encoding_table().shape)
print('get_encoding_table_new: ',get_encoding_table_new().shape)

get_encoding_table:  torch.Size([204, 1, 108])
get_encoding_table_new:  torch.Size([204, 1, 108])


In [36]:
print(get_encoding_table()[:5,0,:4])

tensor([[0.8823, 0.8823, 0.8823, 0.8823],
        [0.0624, 0.0624, 0.0624, 0.0624],
        [0.5723, 0.5723, 0.5723, 0.5723],
        [0.1836, 0.1836, 0.1836, 0.1836],
        [0.3023, 0.3023, 0.3023, 0.3023]])


In [37]:
print(get_encoding_table()[:5,0,:4])

tensor([[0.8823, 0.8823, 0.8823, 0.8823],
        [0.0624, 0.0624, 0.0624, 0.0624],
        [0.5723, 0.5723, 0.5723, 0.5723],
        [0.1836, 0.1836, 0.1836, 0.1836],
        [0.3023, 0.3023, 0.3023, 0.3023]])


In [38]:
print(get_encoding_table_new()[:5,0,:8])

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403,  0.7468,  0.6651,  0.6526,  0.7577,  0.5642,  0.8256],
        [ 0.9093, -0.4161,  0.9933, -0.1153,  0.9889,  0.1483,  0.9317,  0.3633],
        [ 0.1411, -0.9900,  0.5745, -0.8185,  0.8461, -0.5330,  0.9742, -0.2257],
        [-0.7568, -0.6536, -0.2291, -0.9734,  0.2933, -0.9560,  0.6770, -0.7360]])


In [39]:
print(get_encoding_table_new()[:5,0,:4])

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403,  0.7468,  0.6651],
        [ 0.9093, -0.4161,  0.9933, -0.1153],
        [ 0.1411, -0.9900,  0.5745, -0.8185],
        [-0.7568, -0.6536, -0.2291, -0.9734]])


In [1]:
lst=[0.00965196, 0.00965196, 0.0123736, 0.0102107, 0.00818467, 0.00783151, 0.00675935, 0.00857085, 0.0095259, 0.00774765, 0.0108122, 0.0117789, 0.00979316, 0.00873441, 0.010051, 0.00864661, 0.00834376, 0.00957805, 0.00795549, 0.00799048, 0.0091567, 0.00836402, 0.00909901, 0.0106839, 0.00926709, 0.00880724, 0.00818849, 0.00779778, 0.0078845, 0.00788766, 0.00789714, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
print(len(lst))

204


In [4]:
import pandas as pd
import ast

df = pd.read_csv('datasets/WLASL100_train_25fps.csv')
# df = pd.read_csv('Book1.csv')

print(f"Total rows: {len(df)}")

Total rows: 3200


In [ ]:
W=1920
H=1080

keypoints=[]
for row_idx, row in df.iterrows(): # DUYỆT QUA TỪNG HÀNG
    for k in range(0,204):
        for col in row.index: #DUYỆT QUA TỪNG CỘT CỦA HÀNG
            raw_value = row[col]
            try:
                parsed = ast.literal_eval(raw_value)
                keypoints.append(parsed[k])
                if len(parsed) != 204:
                    print(f'Row {row_idx + 1} | Column: {col} | Length: {len(parsed)}')
            except Exception as e:
                # print(f'Row {row_idx + 1} | Column: {col} | Error parsing: {e}')
                continue

        # break
        points=[]
        for i in range(0, len(keypoints), 2):
            points.append([keypoints[i], keypoints[i+1]])
        image = np.zeros((H, W, 3), dtype=np.uint8)

        # Vẽ từng điểm lên ảnh
        for idx,(x_norm, y_norm) in enumerate(points):
            x = int(x_norm * W)
            y = int(y_norm * H)
            if idx==44:
                cv2.circle(image, (x, y), radius=5, color=(255, 255, 255), thickness=-1)
            else:
                cv2.circle(image, (x, y), radius=5, color=(0, 255, 0), thickness=-1)

        # Hoặc lưu ra file
        # cv2.imwrite(f'{k}.png', image)
        cv2.imshow('Image with Keypoints', image)
        if cv2.waitKey(50) & 0xFF == ord('q'):
            break  # Nhấn q để thoát xem sớm
cv2.destroyAllWindows()

In [6]:
cv2.destroyAllWindows()

In [3]:
import pandas as pd
import numpy as np
import ast
import cv2
W=1920
H=1080
df = pd.read_csv('datasets/WLASL100_train_25fps.csv')
# df = pd.read_csv('Book1.csv')

print(f"Total rows: {len(df)}")

Total rows: 3200


In [ ]:

for row_idx, row in df.iterrows():
    parsed_columns = []
    for col in row.index:
        try:
            parsed = ast.literal_eval(row[col])
            parsed_columns.append(parsed)
        except:
            pass

    # Nếu không có đủ dữ liệu
    if not parsed_columns or len(parsed_columns) < 2:
        continue

    frame_index = 30  # chỉ xem frame thứ 30 (hoặc frame bất kỳ bạn muốn)

    points = []
    for i in range(0, len(parsed_columns), 2):  # mỗi cặp X-Y
        try:
            x = parsed_columns[i][frame_index]
            y = parsed_columns[i + 1][frame_index]
            points.append((x, y))            
        except:
            continue

    image = np.zeros((H, W, 3), dtype=np.uint8)

    for idx, (x_norm, y_norm) in enumerate(points):
        x = int(x_norm * W)
        y = int((1 - y_norm) * H)
        color = (255, 255, 255) if idx == 44 else (0, 255, 0)
        cv2.circle(image, (x, y), radius=5, color=color, thickness=-1)

    cv2.putText(image, f'Label: {row_idx}/3200', (10, 30),
                        fontFace=cv2.FONT_HERSHEY_SIMPLEX, fontScale=1,
                        color=(0, 255, 255), thickness=2)
    cv2.imshow('Sign Language Frame', image)
    
    print(f'Đang hiển thị frame thứ {frame_index} của hàng {row_idx}. Nhấn Enter để tiếp tục, Q để thoát.')
    key = cv2.waitKey(0)
    if key == ord('q'):
        break

cv2.destroyAllWindows()


In [48]:
print(points)

[[0.63016, 0.0132794], [0.3878239527306106, 0.26960318367898983], [0.653374, 0.0468509], [0.4072389527306106, 0.2513601836789898], [0.641146, 0.0213176], [0.3960329527306106, 0.26107318367898985], [0.623035, 0.0155153], [0.3826469527306106, 0.2748961836789898], [0.563106, 0.80202], [0.676749, 0.360994], [0.530837, 0.807783], [0.633972, 0.607066], [0.666996, 0.130254], [0.639712, 0.0127442], [0.39080441367533286, 0.23212681023701026], [0.668718, 0.0439014], [0.40629241367533286, 0.21160281023701025], [0.65468, 0.0220652], [0.3948244136753329, 0.22485281023701026], [0.632053, 0.0120381], [0.39053941367533285, 0.23413481023701024], [0.635241, 0.0104069], [0.397369, 0.245507], [0.662136, 0.0435649], [0.402885, 0.237165], [0.648497, 0.015496], [0.396781, 0.24406], [0.628369, 0.00853717], [0.405404, 0.245685], [0.524687, 0.60493], [0.51432, 0.776684], [0.467994, 0.789628], [0.37766, 0.395878], [0.491979, 0.807239], [0.415402, 0.602795], [0.402957, 0.280243], [0.638939, 0.0100516], [0.3874560

In [47]:
print(len(points))

55


In [ ]:
import cv2
import numpy as np

# Tạo ảnh nền đen
image = np.zeros((H, W, 3), dtype=np.uint8)

# Vẽ từng điểm lên ảnh
for x_norm, y_norm in points:
    x = int(x_norm * W)
    y = int(y_norm * H)
    cv2.circle(image, (x, y), radius=5, color=(0, 255, 0), thickness=-1)  # chấm xanh lá

# Hiển thị ảnh (tùy chọn)
cv2.imshow('Points', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Hoặc lưu ra file
cv2.imwrite('points_on_black.png', image)


True

****
dữ liệu

In [2]:
import json

In [31]:
asl100=json.load(open('splits/asl100.json','r'))

In [12]:
asl100

[{'gloss': 'book',
  'instances': [{'bbox': [137, 16, 492, 480],
    'frame_end': 64,
    'frame_start': 1,
    'instance_id': 0,
    'signer_id': 118,
    'source': 'aslbrick',
    'split': 'train',
    'url': 'http://aslbricks.org/New/ASL-Videos/book.mp4',
    'variation_id': 0,
    'video_id': '69241'},
   {'bbox': [137, 16, 492, 480],
    'frame_end': 64,
    'frame_start': 1,
    'instance_id': 1,
    'signer_id': 90,
    'source': 'aslsignbank',
    'split': 'train',
    'url': 'https://aslsignbank.haskins.yale.edu/dictionary/protected_media/glossvideo/BO/BOOK-418.mp4',
    'variation_id': 0,
    'video_id': '65225'},
   {'bbox': [137, 16, 492, 480],
    'frame_end': 47,
    'frame_start': 1,
    'instance_id': 2,
    'signer_id': 110,
    'source': 'valencia-asl',
    'split': 'train',
    'url': 'https://www.youtube.com/watch?v=0UsjUE-TXns',
    'variation_id': 0,
    'video_id': '68011'},
   {'bbox': [137, 16, 492, 480],
    'frame_end': 60,
    'frame_start': 1,
    'instance

In [21]:
video_ids=[]
for x in asl100:
    # print(x['gloss'],end=': ')
    for ins in x['instances']:
        video_ids.append(ins['video_id']+'.mp4')

In [22]:
import os

videos=os.listdir('../WLAST/archive/videos/')

In [24]:
missing=0
for i in video_ids:
    if i not in videos:
        missing+=1

In [25]:
missing

573

In [27]:
asl=json.load(open('splits/all.json','r'))

In [ ]:
asl

****

In [38]:
indexDIP_left_X=[0.640748, 0.640748, 0.640249, 0.638543, 0.639534, 0.638524, 0.639135, 0.63694, 0.638069, 0.638562, 0.634554, 0.634827, 0.635469, 0.633692, 0.632255, 0.630544, 0.632101, 0.632567, 0.636305, 0.636261, 0.633476, 0.63184, 0.629808, 0.630019, 0.629984, 0.629608, 0.629697, 0.62985, 0.63026, 0.630236, 0.63016, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
indexDIP_left_Y=[0.0110954, 0.0110954, 0.010785, 0.0103256, 0.0106089, 0.00947821, 0.0105838, 0.0100782, 0.0147225, 0.0163414, 0.0142441, 0.0162359, 0.0195361, 0.0184913, 0.017674, 0.0182276, 0.0207956, 0.0186844, 0.0248905, 0.024787, 0.0192289, 0.0204983, 0.0142795, 0.01363, 0.0135098, 0.013381, 0.0134565, 0.0137441, 0.0132581, 0.0132633, 0.0132794, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
print(len(indexDIP_left_X))
print(len(indexDIP_left_Y))

204
204


In [5]:
lst1=[0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.55747074,0.55104208,0.5587042 ,0.5647769 ,0.52165729,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.5022822 ,0.50226879,0.49737889,0.        ,0.        ,0.52997321,0.51953018,0.53930998,0.5392049 ,0.        ,0.55856371,0.55909055,0.56179571,0.56348455,0.5620048 ,0.56539094,0.56616795,0.56599218,0.56775302,0.56549066,0.56570584,0.56553459,0.57017171,0.57014543,0.57539976,0.57964653,0.58624834,0.        ,0.59875798,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ]	
lst2=[0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.80128902,0.75054324,0.70268297,0.66948068,0.64852971,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.6398713 ,0.64346069,0.63796365,0.        ,0.        ,0.61591572,0.5931623 ,0.6100952 ,0.60389209,0.        ,0.59889472,0.60080022,0.6047799 ,0.60648453,0.60452682,0.61316907,0.61367089,0.61257976,0.61002249,0.6053493 ,0.60708302,0.60625315,0.61235487,0.61824793,0.62515295,0.66592818,0.71893591,0.        ,0.79566896,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ,0.        ]
print(len(lst1))
print(len(lst2))

78
78


In [30]:
lst=[1.71225226,1.69053626,1.67147088,1.70217657,1.70182157,1.67227364,1.69870472,1.71217632,1.72956777,1.7642864 ,1.79308438,1.78421855,1.78259087,1.77132058,1.73978782,1.71994948,1.76286292,1.71307778,1.71104276,1.72729814,1.74955511,1.76301122,1.77245784,1.7466836 ,1.76340473,1.73010492,1.68546772,1.68110108,1.68141508,1.70183754,1.70603752,1.71325374,1.71036983,1.71511149,1.70595932,1.70278311,1.68305862,1.72567928,1.81140471,1.81099617,1.78938115,1.7504847 ,1.72781873,1.69722056,1.69131899,1.69772923,1.69573569,1.72521663,1.74096417,1.7392199 ,1.74236441,1.7336762 ,1.74279201,1.73044741,1.73034835,1.72854269,1.73063779,1.7257309 ,1.72634089,1.72743928,1.71728063,1.71501613,1.71920586,1.71912849]
print(len(lst))

64


In [1]:
BODY_IDENTIFIERS = [
    "nose", # mũi #
    "neck", # cái cổ #
    "rightEye", # mắt phải #
    "leftEye", # mắt trái  #
    "rightEar", # tai phải #
    "leftEar", # tai trái # 
    "rightShoulder", # vai phải #
    "leftShoulder", # vai trái #
    "rightElbow", # cùi chỏ phải #
    "leftElbow", # cùi chỏ trái #
    "rightWrist", # cổ tay phải  #
    "leftWrist" # cổ tay trái #
]
body_landmarks = {"X": [], "Y": []}

for identifier in BODY_IDENTIFIERS:
    body_landmarks["X"].append(identifier + "_X")
    body_landmarks["Y"].append(identifier + "_Y")

print(body_landmarks)

{'X': ['nose_X', 'neck_X', 'rightEye_X', 'leftEye_X', 'rightEar_X', 'leftEar_X', 'rightShoulder_X', 'leftShoulder_X', 'rightElbow_X', 'leftElbow_X', 'rightWrist_X', 'leftWrist_X'], 'Y': ['nose_Y', 'neck_Y', 'rightEye_Y', 'leftEye_Y', 'rightEar_Y', 'leftEar_Y', 'rightShoulder_Y', 'leftShoulder_Y', 'rightElbow_Y', 'leftElbow_Y', 'rightWrist_Y', 'leftWrist_Y']}
